---
- name : testing copy module with example
  hosts: web
  become: yes
  gather_facts: no
  tasks:
  - name: copying file
    copy:
      src: /home/ansible/devopsus/ansible.cfg
      dest: /home/ansible/ansible.cfg
  - name: install httpd
    yum:
      name: "{{service}}"
      state: present 
  - name: starting httpd
    service:
      name: "{{service}}"
      state: started
...
