- name: lineinefile example
  hosts: db
  become: yes
  vars:
    portnumber: 8080
  tasks:
  - name: install httpd
    package:
      name: httpd
      state: present
  - name: change the port number
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: "Listen {{portnumber}}"
